"""Real disk-cleanup for ephemeral agent-created files -- ported from
Hermes' disk-cleanup plugin. Nancy's own tools already generate real
throwaway files over time (backup zips, scratch scripts, temp downloads);
without this, they'd just accumulate forever. Deletes files matching a glob
under a designated ephemeral directory once they're older than a configured
age -- deliberately narrow (one directory, one age check) rather than a
general-purpose disk scanner, so it can never reach outside the one place
Nancy's own tools are expected to drop temporary output.
"""
from __future__ import annotations

import logging
import time
from pathlib import Path
from typing import Any, Dict

logger = logging.getLogger(__name__)

BACKEND_ROOT = Path(__file__).parent
EPHEMERAL_DIR = BACKEND_ROOT / "data" / "tmp_agent_files"
DEFAULT_MAX_AGE_DAYS = 7.0


def run_cleanup(max_age_days: float = DEFAULT_MAX_AGE_DAYS, pattern: str = "*") -> Dict[str, Any]:
    """Deletes files under EPHEMERAL_DIR matching `pattern` whose mtime is
    older than `max_age_days`. Never touches anything outside EPHEMERAL_DIR,
    and never raises -- a single file that fails to delete (permissions,
    already gone) is logged and skipped, not fatal to the run."""
    if not EPHEMERAL_DIR.exists():
        return {"success": True, "deleted": [], "deleted_count": 0, "freed_bytes": 0}

    cutoff = time.time() - (max_age_days * 86400)
    deleted: list[str] = []
    freed_bytes = 0
    for f in EPHEMERAL_DIR.glob(pattern):
        if not f.is_file():
            continue
        try:
            if f.stat().st_mtime < cutoff:
                size = f.stat().st_size
                f.unlink()
                deleted.append(f.name)
                freed_bytes += size
        except OSError as e:
            logger.warning("disk_cleanup: failed to delete %s: %s", f, e)

    return {"success": True, "deleted": deleted, "deleted_count": len(deleted), "freed_bytes": freed_bytes}


_SCRIPTS_DIR = BACKEND_ROOT / "scripts"
_BOOTSTRAP_SCRIPT_PATH = _SCRIPTS_DIR / "disk_cleanup.py"
_BOOTSTRAP_SCRIPT_SOURCE = '''"""Auto-generated by disk_cleanup.py -- do not hand-edit, it's rewritten on
every backend startup. Real run_script_tool.py entry point for the
disk-cleanup blueprint (see blueprint_catalog.py's "disk-cleanup" entry)."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from disk_cleanup import run_cleanup  # noqa: E402

if __name__ == "__main__":
    result = run_cleanup()
    if result["deleted_count"] == 0:
        print("[SILENT]")
    else:
        print(f"disk_cleanup: removed {result['deleted_count']} file(s), freed {result['freed_bytes']} bytes")
'''


def ensure_bootstrap_script() -> None:
    """Writes scripts/disk_cleanup.py if missing -- scripts/ is entirely
    gitignored (user-dropped-in automation, not committed source), so this
    feature's own run_script_tool.py entry point has to self-install on
    startup rather than ship as a committed file, matching how neu_tts.py
    self-bootstraps its synthetic voice reference clip."""
    _SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    if not _BOOTSTRAP_SCRIPT_PATH.exists():
        _BOOTSTRAP_SCRIPT_PATH.write_text(_BOOTSTRAP_SCRIPT_SOURCE, encoding="utf-8")
        logger.info("disk_cleanup: wrote bootstrap script to %s", _BOOTSTRAP_SCRIPT_PATH)
